### ISSUE TITLE
Usability testing on new design

### ISSUE THREAD

**Issue by jduss4** [18F/gsa-small-business-experience#11]
- [ ] Need testable design (break out)
   - https://github.com/18F/gsa-small-business-experience/issues/61
   -  https://github.com/18F/gsa-small-business-experience/issues/62
- [ ] Testing plan and script
   - https://github.com/18F/gsa-small-business-experience/issues/64
- [ ] Preview design and research plan with OSDBU, FAS, and OSC. 
   - https://github.com/18F/gsa-small-business-experience/issues/65
- [ ] Scheduling and recruiting
   - https://github.com/18F/gsa-small-business-experience/issues/66
- [ ] Do the sessions, debrief, determine what needs iteration
   - https://github.com/18F/gsa-small-business-experience/issues/67

Rough timeline:

- Week of 3/7: explore design and iterate
- Week of 3/14 and 3/21: finalize on content, get SME eyes on it (esp on copy), Jess sync, dev, refine
- Week of 28: actually test

**Comment by janelx** [comment]
is this a duplicate issue of https://github.com/18F/gsa-small-business-experience/issues/67?
