### ISSUE TITLE
Identify opportunity explorer results

### ISSUE THREAD

**Issue by jduss4** [18F/gsa-small-business-experience#68]
Identify/confirm content and paths for opportunity explorer “results”

Goal:
- Confirm requirements
- Are we asking the right questions?
- What are the possible results and what information do we want to present there?

Tasks:
- [x] identify someone at OSDBU who can provide introduction to possible avenues of working with GSA
- [x] for each avenue, select a few criteria for opportunity explorer questions (only IT, only open to HUBZone, etc)
- [x] describe in such a way that it can be coded for prototype
- [x] Create Opportunity explorer document identifying programs, summary and eligibility

**Comment by cmajel** [comment]
From backlog grooming: a cowork session to answer questions on what to display (out of all the things that were identified)
