### ISSUE TITLE
Prep FAS/FMP knowledge center design for usability testing

### ISSUE THREAD

**Issue by 19mderose** [18F/gsa-small-business-experience#89]
Link to [slide](https://docs.google.com/presentation/d/1BEccKLTY6exjL5cGOu4-SnnHS-SgOfBwDYmJCUsScmo/edit#slide=id.g114b6ea2ffd_8_0)
Deadline 3/28

**Comment by janelx** [comment]
Added a link to the design that can be used during usability testing. It's in the script too.
